//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public int IdAdress { get; set; }
        public string Village { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int IdUser { get; set; }
        public virtual User User { get; set; }
    }
}
