//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<User1> User1Set { get; set; }
        public virtual DbSet<YearOfStudy> YearOfStudies { get; set; }
        public virtual DbSet<NewUser> NewUsers { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Cour> Cours { get; set; }
        public virtual DbSet<Event1> Event1Set { get; set; }
        public virtual DbSet<EventsStudent> EventsStudents { get; set; }
        public virtual DbSet<Group1> Group1Set { get; set; }
        public virtual DbSet<Mark1> Mark1Set { get; set; }
        public virtual DbSet<Student1> Student1Set { get; set; }
        public virtual DbSet<Teacher1> Teacher1Set { get; set; }
        public virtual DbSet<User2> User2Set { get; set; }
        public virtual DbSet<YearOfStudy1> YearOfStudy1Set { get; set; }
    }
}
