//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MarkId { get; set; }
        public int CoursId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> Value { get; set; }
    
        public virtual Cour Cour { get; set; }
        public virtual Student Student { get; set; }
    }
}
